name: monas
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  fl_chart: ^0.50.0
  intl: ^0.17.0
  provider: ^6.0.2
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  
  # firebase
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.13
  google_sign_in: ^5.3.0

  # dis play local notification
  flutter_local_notifications: ^9.5.2

  # display contacts in phone
  fast_contacts: ^1.1.1
  permission_handler: ^9.2.0

  # add image from phone
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # native splash screen
  flutter_native_splash: ^2.2.3+1

# Run commands to generate splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/app_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/wallet_ic/
    - assets/icons/category_ic/entertainment/
    - assets/icons/category_ic/incomes/
    - assets/icons/category_ic/investment/
    - assets/icons/category_ic/monthly/
    - assets/icons/category_ic/necessary/
    - assets/icons/category_ic/others/
    - assets/log_in/
    - assets/logo/
    - assets/onboard/
    - assets/icons/others/
    - assets/illustrations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400